import React, { useState, useEffect, useRef } from 'react';
import QRCode from 'qrcode';
import { StoreProfile } from '../../types';

interface OwnerTableQRGeneratorProps {
  storeProfile: StoreProfile;
  onShowToast: (msg: string) => void;
  onSimulateCustomerScan: (tableNumber: number, zone: string) => void;
}

interface GeneratedQRItem {
  id: string;
  tableNumber: number;
  tableName?: string;
  zone: string;
  generatedAt: string;
  qrDataUrl: string;
}

export const OwnerTableQRGenerator: React.FC<OwnerTableQRGeneratorProps> = ({
  storeProfile,
  onShowToast,
  onSimulateCustomerScan,
}) => {
  // Input states for generating a new Menu QR
  const [tableInput, setTableInput] = useState<string>('1');
  const [tableNameInput, setTableNameInput] = useState<string>('');
  const [diningZone, setDiningZone] = useState<string>('Main Dining Room');

  // Currently generated/active QR details
  const [activeTableNumber, setActiveTableNumber] = useState<number>(1);
  const [activeTableName, setActiveTableName] = useState<string>('Table 1');
  const [activeZone, setActiveZone] = useState<string>('Main Dining Room');
  const [activeQrUrl, setActiveQrUrl] = useState<string>('');

  // History list of QRs generated by this owner
  const [generatedList, setGeneratedList] = useState<GeneratedQRItem[]>(() => {
    const saved = localStorage.getItem('sb_generated_qrs');
    if (saved) {
      try {
        return JSON.parse(saved);
      } catch {
        return [];
      }
    }
    return [];
  });

  const printAreaRef = useRef<HTMLDivElement>(null);

  const zones = [
    'Main Dining Room',
    'Outdoor Patio Terrace',
    'Ember Bar & High-Top',
    'Booth Row A',
    'Private Event Nook',
    'Rooftop Deck',
    'Counter Seats',
  ];

  // Base URL pointing to this applet
  const baseUrl = typeof window !== 'undefined'
    ? `${window.location.origin}${window.location.pathname}`
    : 'https://sizzle-and-bun.restaurant';

  const customerTargetUrl = `${baseUrl}?table=${activeTableNumber}&zone=${encodeURIComponent(activeZone)}`;

  // Generate QR for active table whenever it changes
  useEffect(() => {
    QRCode.toDataURL(customerTargetUrl, {
      width: 400,
      margin: 1.5,
      color: {
        dark: '#1e1b19',
        light: '#ffffff',
      },
      errorCorrectionLevel: 'H',
    })
      .then((url) => {
        setActiveQrUrl(url);
      })
      .catch((err) => console.error(err));
  }, [customerTargetUrl]);

  // Save history to localStorage
  useEffect(() => {
    localStorage.setItem('sb_generated_qrs', JSON.stringify(generatedList));
  }, [generatedList]);

  // Owner clicks "Generate Menu QR"
  const handleGenerateQR = (e: React.FormEvent) => {
    e.preventDefault();
    const num = parseInt(tableInput, 10);
    if (isNaN(num) || num <= 0) {
      onShowToast('Please enter a valid table number (e.g. 1, 2, 5)');
      return;
    }

    const displayName = tableNameInput.trim() || `Table #${num}`;
    setActiveTableNumber(num);
    setActiveTableName(displayName);
    setActiveZone(diningZone);

    const target = `${baseUrl}?table=${num}&zone=${encodeURIComponent(diningZone)}`;
    QRCode.toDataURL(target, {
      width: 400,
      margin: 1.5,
      color: { dark: '#1e1b19', light: '#ffffff' },
      errorCorrectionLevel: 'H',
    }).then((url) => {
      setActiveQrUrl(url);

      // Add to generated history if not already present
      setGeneratedList((prev) => {
        const filtered = prev.filter((item) => item.tableNumber !== num);
        const newItem: GeneratedQRItem = {
          id: `qr-${num}-${Date.now()}`,
          tableNumber: num,
          tableName: displayName,
          zone: diningZone,
          generatedAt: new Date().toLocaleDateString([], { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' }),
          qrDataUrl: url,
        };
        return [newItem, ...filtered];
      });

      onShowToast(`Menu QR for ${displayName} generated successfully!`);
    });
  };

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadQR = () => {
    if (!activeQrUrl) return;
    const a = document.createElement('a');
    a.href = activeQrUrl;
    a.download = `${storeProfile.name.replace(/\s+/g, '_')}_Table_${activeTableNumber}_Menu_QR.png`;
    a.click();
    onShowToast(`Saved Menu QR image for Table #${activeTableNumber}`);
  };

  const handleCopyLink = () => {
    navigator.clipboard?.writeText(customerTargetUrl);
    onShowToast(`Customer Menu link for Table #${activeTableNumber} copied!`);
  };

  const handleSelectFromHistory = (item: GeneratedQRItem) => {
    setActiveTableNumber(item.tableNumber);
    setActiveTableName(item.tableName || `Table #${item.tableNumber}`);
    setActiveZone(item.zone);
    setTableInput(item.tableNumber.toString());
    setDiningZone(item.zone);
    onShowToast(`Loaded ${item.tableName || `Table #${item.tableNumber}`}`);
  };

  const handleRemoveFromHistory = (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    setGeneratedList((prev) => prev.filter((i) => i.id !== id));
    onShowToast('Removed from history.');
  };

  return (
    <div className="space-y-6">
      {/* Print-specific CSS styles */}
      <style>{`
        @media print {
          body * {
            visibility: hidden;
          }
          #printable-qr-stand, #printable-qr-stand * {
            visibility: visible;
          }
          #printable-qr-stand {
            position: absolute;
            left: 50%;
            top: 50%;
            transform: translate(-50%, -50%);
            width: 100%;
            max-width: 440px;
            box-shadow: none !important;
            border: 2px solid #ddd !important;
          }
        }
      `}</style>

      {/* Header Banner */}
      <div className="bg-surface-container-lowest p-6 rounded-3xl shadow-xs border border-black/[0.04] flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="material-symbols-outlined text-primary text-2xl">qr_code_2</span>
            <h2 className="font-headline-md text-xl text-on-surface font-black">
              Customer Menu QR Generator
            </h2>
            <span className="px-2.5 py-0.5 rounded-full bg-primary/10 text-primary text-[10px] font-black uppercase">
              Digital Order &amp; Pay
            </span>
          </div>
          <p className="font-body-sm text-xs text-on-surface-variant max-w-xl">
            Generate unique QR codes for any dining table. When customers scan it, they see your restaurant name, floating animated logo, digital menu, live kitchen tracking, and contactless bill payment.
          </p>
        </div>

        {activeQrUrl && (
          <div className="flex items-center gap-2">
            <button
              onClick={handlePrint}
              className="px-4 py-2.5 rounded-xl bg-neutral-900 hover:bg-neutral-800 text-white text-xs font-bold flex items-center gap-1.5 shadow-sm active:scale-95 transition-all"
            >
              <span className="material-symbols-outlined text-[16px]">print</span>
              <span>Print Table Card</span>
            </button>
            <button
              onClick={() => onSimulateCustomerScan(activeTableNumber, activeZone)}
              className="px-4 py-2.5 rounded-xl bg-primary hover:bg-primary-container text-on-primary text-xs font-bold flex items-center gap-1.5 shadow-sm active:scale-95 transition-all"
            >
              <span className="material-symbols-outlined text-[16px]">phone_android</span>
              <span>Test Customer View</span>
            </button>
          </div>
        )}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
        {/* Left Column: Generator Form & History */}
        <div className="lg:col-span-6 space-y-6">
          {/* Generation Form */}
          <div className="bg-surface-container-lowest p-6 rounded-3xl shadow-xs border border-black/[0.04] space-y-5">
            <div className="flex items-center justify-between border-b border-black/[0.04] pb-3">
              <h3 className="font-headline-md text-base text-on-surface font-extrabold flex items-center gap-2">
                <span className="material-symbols-outlined text-primary text-xl">add_circle</span>
                Generate Table QR
              </h3>
              <span className="text-[11px] text-on-surface-variant">
                Enter details to create unique QR
              </span>
            </div>

            <form onSubmit={handleGenerateQR} className="space-y-4">
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                {/* Table Number */}
                <div>
                  <label className="font-label-sm text-on-surface-variant block mb-1">
                    Table Number *
                  </label>
                  <input
                    type="number"
                    min="1"
                    max="500"
                    required
                    value={tableInput}
                    onChange={(e) => setTableInput(e.target.value)}
                    placeholder="e.g. 1, 4, 12"
                    className="w-full px-3.5 py-2.5 rounded-xl bg-surface-container text-on-surface text-base font-bold outline-none border border-black/10 focus:border-primary"
                  />
                  <span className="text-[11px] text-on-surface-variant mt-1 block">
                    Assigned dining table number
                  </span>
                </div>

                {/* Table Label / Custom Name */}
                <div>
                  <label className="font-label-sm text-on-surface-variant block mb-1">
                    Custom Name / Label (Optional)
                  </label>
                  <input
                    type="text"
                    value={tableNameInput}
                    onChange={(e) => setTableNameInput(e.target.value)}
                    placeholder="e.g. Patio Booth 2, VIP Nook"
                    className="w-full px-3.5 py-2.5 rounded-xl bg-surface-container text-on-surface text-sm font-medium outline-none border border-black/10 focus:border-primary"
                  />
                  <span className="text-[11px] text-on-surface-variant mt-1 block">
                    Printed on the table tent
                  </span>
                </div>
              </div>

              {/* Dining Zone */}
              <div>
                <label className="font-label-sm text-on-surface-variant block mb-1">
                  Dining Room Zone / Location
                </label>
                <select
                  value={diningZone}
                  onChange={(e) => setDiningZone(e.target.value)}
                  className="w-full px-3.5 py-2.5 rounded-xl bg-surface-container text-on-surface text-sm font-semibold outline-none border border-black/10"
                >
                  {zones.map((z) => (
                    <option key={z} value={z}>{z}</option>
                  ))}
                </select>
              </div>

              {/* Generate Button */}
              <button
                type="submit"
                className="w-full py-3.5 rounded-2xl bg-primary hover:bg-primary-container text-on-primary font-headline-md text-sm font-extrabold flex items-center justify-center gap-2 shadow-md active:scale-95 transition-all"
              >
                <span className="material-symbols-outlined text-xl">qr_code_scanner</span>
                <span>Generate Menu QR Code</span>
              </button>
            </form>
          </div>

          {/* Recently Generated QRs by Owner */}
          {generatedList.length > 0 && (
            <div className="bg-surface-container-lowest p-6 rounded-3xl shadow-xs border border-black/[0.04] space-y-4">
              <div className="flex items-center justify-between">
                <h4 className="font-headline-md text-sm text-on-surface font-extrabold flex items-center gap-1.5">
                  <span className="material-symbols-outlined text-[18px] text-primary">history</span>
                  Your Generated Menu QRs ({generatedList.length})
                </h4>
                <button
                  onClick={() => {
                    if (confirm('Clear generated QR history?')) {
                      setGeneratedList([]);
                      onShowToast('History cleared.');
                    }
                  }}
                  className="text-[11px] text-on-surface-variant hover:text-error"
                >
                  Clear History
                </button>
              </div>

              <div className="space-y-2 max-h-72 overflow-y-auto pr-1">
                {generatedList.map((item) => (
                  <div
                    key={item.id}
                    onClick={() => handleSelectFromHistory(item)}
                    className={`p-3 rounded-2xl border transition-all flex items-center justify-between gap-3 cursor-pointer ${
                      activeTableNumber === item.tableNumber
                        ? 'border-primary bg-primary/[0.03] shadow-xs'
                        : 'border-black/[0.04] bg-surface-container/40 hover:bg-surface-container'
                    }`}
                  >
                    <div className="flex items-center gap-3 min-w-0">
                      <div className="w-10 h-10 rounded-xl bg-white p-1 border border-black/5 shadow-xs flex-shrink-0 flex items-center justify-center">
                        {item.qrDataUrl ? (
                          <img src={item.qrDataUrl} alt="QR Thumbnail" className="w-full h-full object-contain" />
                        ) : (
                          <span className="material-symbols-outlined text-neutral-400 text-base">qr_code_2</span>
                        )}
                      </div>
                      <div className="min-w-0">
                        <div className="flex items-center gap-2">
                          <span className="font-headline-md text-sm text-on-surface font-bold truncate">
                            {item.tableName || `Table #${item.tableNumber}`}
                          </span>
                          <span className="text-[10px] bg-secondary-fixed text-on-secondary-fixed px-2 py-0.2 rounded-full font-bold">
                            {item.zone}
                          </span>
                        </div>
                        <span className="text-[11px] text-on-surface-variant block mt-0.5">
                          Generated {item.generatedAt}
                        </span>
                      </div>
                    </div>

                    <div className="flex items-center gap-1 flex-shrink-0">
                      <button
                        onClick={(e) => {
                          e.stopPropagation();
                          onSimulateCustomerScan(item.tableNumber, item.zone);
                        }}
                        title="Test Customer Menu"
                        className="p-1.5 rounded-lg bg-surface-container hover:bg-surface-container-high text-on-surface-variant hover:text-primary transition-colors"
                      >
                        <span className="material-symbols-outlined text-[16px]">phone_android</span>
                      </button>
                      <button
                        onClick={(e) => handleRemoveFromHistory(item.id, e)}
                        title="Remove"
                        className="p-1.5 rounded-lg bg-surface-container hover:bg-surface-container-high text-on-surface-variant hover:text-error transition-colors"
                      >
                        <span className="material-symbols-outlined text-[16px]">delete</span>
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* Right Column: Scannable Stand Card Preview */}
        <div className="lg:col-span-6 flex flex-col items-center">
          <div className="w-full max-w-sm">
            <div className="flex items-center justify-between mb-2 px-1">
              <span className="font-headline-md text-xs uppercase tracking-wider text-on-surface-variant font-bold">
                Table Card Print Preview
              </span>
              <span className="text-xs text-primary font-bold">
                {activeTableName}
              </span>
            </div>

            {/* PRINTABLE CARD */}
            <div
              id="printable-qr-stand"
              ref={printAreaRef}
              className="bg-white rounded-3xl shadow-xl border border-black/10 overflow-hidden text-center flex flex-col transition-all"
            >
              {/* Header with store brand name & uploaded logo */}
              <div className="bg-primary text-white py-4 px-4 flex flex-col items-center">
                <div className="flex items-center justify-center gap-2.5 mb-1">
                  <div className="w-10 h-10 rounded-xl bg-white p-1 shadow-xs flex items-center justify-center flex-shrink-0 overflow-hidden">
                    {storeProfile.logoUrl ? (
                      <img
                        src={storeProfile.logoUrl}
                        alt={storeProfile.name}
                        className="w-full h-full object-contain"
                      />
                    ) : (
                      <span className="material-symbols-outlined text-primary text-2xl">restaurant</span>
                    )}
                  </div>
                  <span className="font-headline-md text-base font-black text-white truncate max-w-[220px]">
                    {storeProfile.name}
                  </span>
                </div>
                <p className="font-label-sm text-[10px] uppercase tracking-widest text-white/80 font-bold">
                  Scan to Order &amp; Pay Digital Bill
                </p>
              </div>

              {/* Table Identification */}
              <div className="pt-4 pb-1">
                <span className="inline-block px-3 py-0.5 rounded-full bg-neutral-100 text-neutral-800 font-label-sm text-[10px] uppercase tracking-wider font-extrabold border border-neutral-200">
                  {activeZone}
                </span>
                <h3 className="font-headline-xl text-3xl font-black text-neutral-900 mt-1">
                  {activeTableName}
                </h3>
                <p className="text-[11px] text-neutral-500 mt-0.5 px-4 truncate">
                  {storeProfile.tagline}
                </p>
              </div>

              {/* Scannable QR Code */}
              <div className="flex flex-col items-center justify-center p-3">
                <div className="p-3 bg-white rounded-2xl shadow-inner border-2 border-primary/20 relative">
                  {activeQrUrl ? (
                    <img
                      src={activeQrUrl}
                      alt={`Menu QR for Table ${activeTableNumber}`}
                      className="w-56 h-56 object-contain"
                    />
                  ) : (
                    <div className="w-56 h-56 flex items-center justify-center text-xs text-neutral-400">
                      Generating QR Code...
                    </div>
                  )}

                  {/* Brand Center Logo Badge */}
                  <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-12 h-12 rounded-2xl bg-white p-1 flex items-center justify-center shadow-xl border-2 border-primary overflow-hidden pointer-events-none">
                    {storeProfile.logoUrl ? (
                      <img
                        src={storeProfile.logoUrl}
                        alt={storeProfile.name}
                        className="w-full h-full object-contain"
                      />
                    ) : (
                      <span className="material-symbols-outlined text-primary text-2xl">restaurant</span>
                    )}
                  </div>
                </div>

                {/* Steps */}
                <div className="mt-2.5 flex items-center gap-1.5 text-primary font-label-md text-xs uppercase tracking-wider font-extrabold">
                  <span className="material-symbols-outlined text-[16px]">qr_code_scanner</span>
                  <span>1. Scan • 2. Order • 3. Pay Contactless</span>
                </div>
              </div>

              {/* WiFi Credentials if configured */}
              {storeProfile.wifiName && (
                <div className="mx-4 mb-2 p-2 rounded-xl bg-neutral-50 border border-neutral-100 text-xs flex justify-around text-neutral-700 font-medium">
                  <span>WiFi: <strong className="text-neutral-900">{storeProfile.wifiName}</strong></span>
                  <span>Pass: <strong className="text-neutral-900">{storeProfile.wifiPassword}</strong></span>
                </div>
              )}

              {/* Payment note */}
              <div className="bg-neutral-900 text-white py-2 px-3 text-[11px] font-bold">
                UPI ID: {storeProfile.upiId} • Cash in Counter Supported
              </div>
            </div>

            {/* Quick Actions Under Card */}
            <div className="w-full mt-4 grid grid-cols-3 gap-2">
              <button
                onClick={handlePrint}
                className="py-2.5 px-2 rounded-xl bg-neutral-900 hover:bg-neutral-800 text-white text-xs font-bold flex items-center justify-center gap-1 shadow-sm active:scale-95 transition-all"
              >
                <span className="material-symbols-outlined text-[16px]">print</span>
                <span>Print Card</span>
              </button>
              <button
                onClick={handleDownloadQR}
                className="py-2.5 px-2 rounded-xl bg-surface-container hover:bg-surface-container-high text-on-surface text-xs font-bold flex items-center justify-center gap-1 active:scale-95 transition-all"
              >
                <span className="material-symbols-outlined text-[16px]">download</span>
                <span>Save PNG</span>
              </button>
              <button
                onClick={handleCopyLink}
                className="py-2.5 px-2 rounded-xl bg-surface-container hover:bg-surface-container-high text-on-surface text-xs font-bold flex items-center justify-center gap-1 active:scale-95 transition-all"
              >
                <span className="material-symbols-outlined text-[16px]">share</span>
                <span>Copy Link</span>
              </button>
            </div>

            {/* Direct Test Customer Menu Trigger */}
            <button
              onClick={() => onSimulateCustomerScan(activeTableNumber, activeZone)}
              className="w-full mt-2 py-3 rounded-xl bg-secondary-container hover:bg-secondary hover:text-white text-on-secondary-container text-xs font-bold flex items-center justify-center gap-2 active:scale-95 transition-all shadow-xs"
            >
              <span className="material-symbols-outlined text-[18px]">phone_android</span>
              <span>Test Customer Ordering Experience (Table #{activeTableNumber})</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
